apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-backend.fullname" . }}-secrets
  labels:
    {{- include "todo-backend.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.anthropicApiKey }}
  ANTHROPIC_API_KEY: {{ .Values.secrets.anthropicApiKey | b64enc | quote }}
  {{- else }}
  ANTHROPIC_API_KEY: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.openaiApiKey | b64enc | quote }}
  {{- else }}
  OPENAI_API_KEY: {{ "" | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.jwtSecretKey }}
  JWT_SECRET_KEY: {{ .Values.secrets.jwtSecretKey | b64enc | quote }}
  {{- else }}
  JWT_SECRET_KEY: {{ "default-jwt-secret-key-for-development" | b64enc | quote }}
  {{- end }}
