# Redis State Store Component
# Used for caching and state management
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: todo-phase5
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: "redis.todo-phase5.svc.cluster.local:6379"
    - name: redisPassword
      value: ""
    - name: enableTLS
      value: "false"
    - name: actorStateStore
      value: "true"
scopes:
  - backend
  - notification-service
